# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install allure-pytest
    - name: Setup Allure TestOps
      # You may pin to the exact commit or the version.
      # uses: allure-framework/setup-allurectl@6878686fce27aeb6f49009173b2947a400e282b5
      uses:  allure-framework/setup-allurectl@v1.0.0
               
    - name: Test with pytest
      run: |
        pytest -v --alluredir=report/suite
